version: '3.8'

services:
  rest-api:
    image: rest-api-films
    container_name: rest_api
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restapi
